version: "3"
services:
  app:
    build: .
    networks:
      - backend
    links:
      - db
    command: ["sh", "start.sh"]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    environment: # Adicione as variáveis de ambiente aqui
      DB_NAME: cmmts-delivery
      DB_USER: commits
      DB_PASSWORD: mccts@24
      DB_HOST: db # Use 'db' como o hostname
      DB_DIALECT: postgres
      DB_PORT: 5432
  db:
    image: postgres
    networks:
      - backend
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cmmts-delivery
      POSTGRES_USER: commits
      POSTGRES_PASSWORD: mccts@24
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  node_modules:

networks:
  backend:
    name: backend
    driver: bridge
    external: true
